name: WarlordsPartyManager
version: ${project.artifactId}
main: com.github.ebicep.warlordspartymanager.WarlordsPartyManager
depend:
  - Warlords
commands:
  party:
    description: Party options
    aliases:
      - p
      - party