name: WarlordsPartyManager
version: ${project.version}
main: com.ebicep.warlordspartymanager.WarlordsPartyManager
softdepend:
  - Warlords
commands:
  party:
    description: Party options
    aliases:
      - party
      - p
  stream:
    description: Creates a new party where anyone can join
    usage: /stream